# Generated by Django 5.2.4 on 2025-07-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_vehicle_description_vehicle_is_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('chauffeur', 'Chauffeur'), ('loueur', 'Loueur'), ('manager_staff', 'Manager Staff'), ('employee_staff', 'Employé Staff')], default='client', max_length=20),
        ),
    ]
