# Generated by Django 5.2.4 on 2025-08-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_full_name_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
