# Generated by Django 5.2.4 on 2025-08-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
