# Generated by Django 5.2.4 on 2025-08-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='default_driver@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='driver',
            name='role',
            field=models.CharField(default='chauffeur', max_length=50),
        ),
    ]
