# Generated by Django 5.2.4 on 2025-08-17 15:58

import drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_category_driver_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='id_card_file',
            field=models.FileField(blank=True, null=True, upload_to=drivers.models.driver_upload_path),
        ),
        migrations.AddField(
            model_name='driver',
            name='insurance_file',
            field=models.FileField(blank=True, null=True, upload_to=drivers.models.driver_upload_path),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to=drivers.models.driver_upload_path),
        ),
    ]
