# Generated by Django 5.2.4 on 2025-08-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_accepted_terms_driver_id_card_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
