# Generated by Django 5.2.4 on 2025-08-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_driver_is_online_driver_last_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-created_at']},
        ),
    ]
