# Generated by Django 5.2.4 on 2025-08-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_driver_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={},
        ),
    ]
