# Generated by Django 5.2.4 on 2025-10-14 03:44

import django.db.models.deletion
import drivers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_alter_driver_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_file', models.FileField(blank=True, null=True, upload_to=drivers.models.upload_to_driver)),
                ('insurance_file', models.FileField(blank=True, null=True, upload_to=drivers.models.upload_to_driver)),
                ('registration_file', models.FileField(blank=True, null=True, upload_to=drivers.models.upload_to_driver)),
                ('id_card_file', models.FileField(blank=True, null=True, upload_to=drivers.models.upload_to_driver)),
                ('status', models.CharField(choices=[('missing', 'Manquant'), ('pending', 'En cours'), ('approved', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
