# Generated by Django 5.2.4 on 2025-11-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_driverdocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='block_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
