# Generated by Django 5.2.4 on 2025-07-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('transmission', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybrid', 'Hybride'), ('electric', 'Électrique')], max_length=20)),
                ('seats', models.PositiveIntegerField()),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
            ],
        ),
    ]
