# Generated by Django 5.2.4 on 2025-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('SUV', 'SUV'), ('4x4', '4x4'), ('Berline', 'Berline'), ('Citadine', 'Citadine')], default='Berline', max_length=50),
            preserve_default=False,
        ),
    ]
