# Generated by Django 5.2.4 on 2025-07-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='city',
            field=models.CharField(default='Libreville', max_length=100),
            preserve_default=False,
        ),
    ]
