# Generated by Django 5.2.4 on 2025-08-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_created_at_vehicle_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
