# Generated by Django 5.2.4 on 2025-10-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_owner_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('cta', models.CharField(blank=True, max_length=60, verbose_name='CTA label')),
                ('url', models.URLField(blank=True, verbose_name='CTA URL')),
                ('badge', models.CharField(blank=True, max_length=24)),
                ('image', models.ImageField(blank=True, upload_to='rental_promos/')),
                ('city', models.CharField(blank=True, help_text='Si rempli, promo ciblée sur cette ville (insensible à la casse). Laisser vide = globale.', max_length=80, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Plus grand = plus prioritaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-updated_at', '-id'],
            },
        ),
    ]
