# Generated by Django 5.2.4 on 2025-10-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehiclebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='identification_code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
