# Generated by Django 5.2.4 on 2025-11-16 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_rental_identification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('wallet', models.CharField(default='MOBILE_MONEY', max_length=32)),
                ('msisdn', models.CharField(blank=True, max_length=32, null=True)),
                ('provider', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué')], default='PENDING', max_length=16)),
                ('provider_txid', models.CharField(blank=True, max_length=128, null=True)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vehicles.rental')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
