# Generated by Django 5.2.4 on 2025-08-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideVTC', '0003_ride_dropoff_lat_ride_dropoff_lng_ride_pickup_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='category',
            field=models.CharField(default='eco', max_length=10),
        ),
    ]
