# Generated by Django 5.2.4 on 2025-08-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideVTC', '0004_ride_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='category',
            field=models.CharField(choices=[('eco', 'Éco'), ('clim', 'Clim'), ('vip', 'VIP')], default='eco', max_length=10),
        ),
    ]
