# Generated by Django 5.2.4 on 2025-08-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideVTC', '0005_alter_ride_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='category',
        ),
    ]
