# Generated by Django 5.2.4 on 2025-09-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideVTC', '0006_remove_ride_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
