# Generated by Django 5.2.4 on 2025-10-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideVTC', '0007_ride_driver_lat_ride_driver_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('wallet', models.CharField(default='MOBILE_MONEY', max_length=20)),
                ('msisdn', models.CharField(max_length=32)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('provider', models.CharField(max_length=32)),
                ('provider_txid', models.CharField(blank=True, max_length=128, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideVTC.ride')),
            ],
        ),
    ]
