# Generated by Django 5.2.4 on 2025-10-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideVTC', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='msisdn',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('AIRTEL_MONEY', 'Airtel Money')], default='AIRTEL_MONEY', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='RideVTC.ride'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='wallet',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BLAZE', 'Blaze Wallet')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['idempotency_key'], name='RideVTC_pay_idempot_ac0ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_txid'], name='RideVTC_pay_provide_6e6ed9_idx'),
        ),
    ]
