# Generated by Django 5.2.4 on 2025-10-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideVTC', '0010_ride_customer_comment_ride_customer_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridevehicle',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ridevehicle',
            name='insurance_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridevehicle',
            name='plate',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ridevehicle',
            name='technical_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridevehicle',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
