# Generated by Django 5.2.4 on 2025-10-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideVTC', '0012_driverpresence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('AIRTEL_MONEY', 'Airtel Money'), ('CASH', 'Cash')], default='AIRTEL_MONEY', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='wallet',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BLAZE', 'Blaze Wallet'), ('CASH', 'Cash')], max_length=16),
        ),
    ]
