# Generated by Django 5.2.4 on 2025-10-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideVTC', '0013_alter_payment_provider_alter_payment_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pause_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='pause_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='total_pause_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
