# Generated by Django 5.2.4 on 2025-10-29 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideVTC', '0014_ride_final_price_ride_pause_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverNavEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('nav_started', 'Nav Started'), ('reroute', 'Reroute'), ('off_route', 'Off Route'), ('eta_update', 'Eta Update'), ('arrived_pickup', 'Arrived Pickup'), ('arrived_dropoff', 'Arrived Dropoff'), ('pause_nav', 'Pause Nav'), ('resume_nav', 'Resume Nav'), ('error', 'Error')], db_index=True, max_length=32)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ridevtc_nav_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'created_at'], name='RideVTC_dri_driver__84791a_idx'), models.Index(fields=['request_id', 'created_at'], name='RideVTC_dri_request_283b21_idx')],
            },
        ),
    ]
